-- 创建数据库base
CREATE DATABASE base;
-- 切换数据库base
use base;

-- 创建系统用户表
CREATE TABLE USERS (
	`USER_ID` INT NOT NULL AUTO_INCREMENT COMMENT '系统用户ID',
	`USER_NAME` CHAR(255) NOT NULL COMMENT '系统用户登录名',
	`PASSWORD_MD5` VARCHAR(64) NOT NULL COMMENT '系统用户登录密码',
	`LOGIN_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '系统用户最后登录时间',
	PRIMARY KEY (USER_ID),
	KEY IDX_USER_NAME(USER_NAME),
	KEY IDX_PASSWORD_MD5(PASSWORD_MD5)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT='系统用户表';

-- 创建用户信息表
CREATE TABLE USER_INFO(
	`USER_INFO_ID` INT NOT NULL COMMENT '用户信息ID',
	`USER_ID` INT NOT NULL COMMENT '关联USER表ID',
	`NICKNAME` CHAR(255) NOT NULL COMMENT '昵称',
	`PHONE_NUMBER` CHAR(255) COMMENT '电话号码',
	`EMAIL` CHAR(255) COMMENT '电子邮箱',
	PRIMARY KEY (USER_INFO_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
	KEY IDX_NICKNAME (NICKNAME)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT '用户信息表';

-- 创建文章类型表
CREATE TABLE ARTICLE_TYPE(
	`ARTICLE_TYPE_ID` INT NOT NULL COMMENT '文章类型ID',
	`ARTICLE_TYPE_NAME` CHAR(255) NOT NULL COMMENT '文章类型名称',
	`USER_ID` INT NOT NULL COMMENT '所属用户',
	PRIMARY KEY (ARTICLE_TYPE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
	KEY IDX_ARTICLE_TYPE_NAME(ARTICLE_TYPE_NAME)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT '文章类型表';

-- 创建文章表
CREATE TABLE ARTICLE(
	`ARTICLE_ID` INT NOT NULL COMMENT '文章ID',
	`ARTICLE_TYPE_ID` INT NOT NULL COMMENT '关联文章类型ID',
	`EDITOR_TYPE` TINYINT NOT NULL DEFAULT 0 COMMENT '编辑器类型0为富文本编辑器,1为Markdown编辑器',
	`ARTICLE_STATE` TINYINT NOT NULL DEFAULT 0 COMMENT '文章发布状态0为未发布,1为发布',
	`ARTICLE_CONTENT` BLOB NOT NULL COMMENT '文章内容',
	`PREV_ARTICLE_ID` INT NOT NULL COMMENT '上一篇文章ID',
	`NEXT_ARTICLE_ID` INT NOT NULL COMMENT '下一篇文章ID',
	`KEYWORDS` CHAR(255) NOT NULL DEFAULT '' COMMENT '关键词',
	`CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '文章创建时间',
	`MODIFY_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '文章最后修改时间',
	PRIMARY KEY (ARTICLE_ID),
	FOREIGN KEY (PREV_ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID),
	FOREIGN KEY (NEXT_ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT '文章表';

-- 创建附件表
CREATE TABLE ATTACHMENT (
	`ATTACHMENT_ID` INT NOT NULL COMMENT '附件ID',
	`ARTICLE_ID` INT NOT NULL COMMENT '关联文章ID',
	`ATTACHMENT_NAME` CHAR(255) NOT NULL COMMENT '附件名',
	`ATTACHMENT_CONTENT` BLOB NOT NULL COMMENT '附件内容',
	PRIMARY KEY (ATTACHMENT_ID),
	FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID),
	KEY IDX_ATTACHMENT_NAME (ATTACHMENT_NAME)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT '附件表';

-- 创建回复表
CREATE TABLE REPLY(
	`REPLY_ID` INT NOT NULL COMMENT '回复ID',
	`ARTICLE_ID` INT NOT NULL COMMENT '关联文章ID',
	`REPLYER_NAME` CHAR(255) NOT NULL COMMENT '回复者名',
	`REPLY_CONTENT` VARCHAR(6000) NOT NULL COMMENT '回复内容',
	`REPLY_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复时间',
	`PARENT_REPLY_ID` INT COMMENT '父级回复',
	PRIMARY KEY (REPLY_ID),
	FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID),
	FOREIGN KEY (PARENT_REPLY_ID) REFERENCES REPLY (REPLY_ID),
	KEY IDX_REPLYER_NAME(REPLYER_NAME),
	KEY IDX_REPLY_TIME(REPLY_TIME)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT '回复表';

-- 创建日志表
CREATE TABLE LOGS (
	`LOG_ID` INT NOT NULL COMMENT '日志ID',
	`REQUEST` VARCHAR(600) NOT NULL COMMENT '请求URL',
	`PARAMS` VARCHAR(1000) COMMENT '请求参数',
	`TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日志插入时间',
	PRIMARY KEY (LOG_ID)
)ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=UTF8 COMMENT '日志表';